### ISSUE TITLE
Is there a reason why the originating project has not supported .NET standard?

### ISSUE THREAD

**Issue by pjmagee** [DurtyFree/obs-websocket-dotnet#1]
Thank you for the port :)

**Comment by DurtyFree** [comment]
Hey! I think the reason is that its basically building upon a websocket library that doesnt support .NET Standard. I had to replace it. (Maybe now they also support .NET Standard but I am not sure)

My port was also updated with all available OBS WebSocket APIs at that point, not sure if its still up2date tho.
